;
CREATE USER IF NOT EXISTS "SA" SALT '66e8e94c7d2f671b' HASH '9e0c9a567ad156b1e6f0f5cc8eceb6c062a12f816b42192b6ae7fafd6649c230' ADMIN;
CREATE CACHED TABLE "PUBLIC"."MINISTER"(
                                           "ID" BINARY NOT NULL,
                                           "NAME" VARCHAR(255)
);
ALTER TABLE "PUBLIC"."MINISTER" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_D" PRIMARY KEY("ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.MINISTER;
CREATE CACHED TABLE "PUBLIC"."PASSWORD_RESET_TOKEN"(
                                                       "ID" BINARY NOT NULL,
                                                       "EXPIRY_DATE" TIMESTAMP,
                                                       "TOKEN" VARCHAR(255),
                                                       "USER_ID" BINARY NOT NULL
);
ALTER TABLE "PUBLIC"."PASSWORD_RESET_TOKEN" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_C" PRIMARY KEY("ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.PASSWORD_RESET_TOKEN;
CREATE CACHED TABLE "PUBLIC"."PRIVILEGE"(
                                            "ID" BINARY NOT NULL,
                                            "NAME" VARCHAR(255)
);
ALTER TABLE "PUBLIC"."PRIVILEGE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4" PRIMARY KEY("ID");
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.PRIVILEGE;
INSERT INTO "PUBLIC"."PRIVILEGE" VALUES
(X'769b513d55f1467f8de576ec7ba3b23e', 'SUPERUSER');
CREATE CACHED TABLE "PUBLIC"."ROLE"(
                                       "ID" BINARY NOT NULL,
                                       "NAME" VARCHAR(255)
);
ALTER TABLE "PUBLIC"."ROLE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_2" PRIMARY KEY("ID");
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.ROLE;
INSERT INTO "PUBLIC"."ROLE" VALUES
(X'e536a769267141a38059187ab8ea1938', 'ADMIN');
CREATE CACHED TABLE "PUBLIC"."ROLES_PRIVILEGES"(
                                                   "ROLE_ID" BINARY NOT NULL,
                                                   "PRIVILEGE_ID" BINARY NOT NULL
);
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.ROLES_PRIVILEGES;
INSERT INTO "PUBLIC"."ROLES_PRIVILEGES" VALUES
(X'e536a769267141a38059187ab8ea1938', X'769b513d55f1467f8de576ec7ba3b23e');
CREATE CACHED TABLE "PUBLIC"."TERRITORY"(
                                            "ID" BINARY NOT NULL,
                                            "NAME" VARCHAR(255),
                                            "NUMBER" VARCHAR(255),
                                            "URL_FOR_GOOGLE_MAP" VARCHAR(255),
                                            "URL_FOR_JPEG_MAP" VARCHAR(255)
);
ALTER TABLE "PUBLIC"."TERRITORY" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_27" PRIMARY KEY("ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.TERRITORY;
CREATE CACHED TABLE "PUBLIC"."TERRITORY_ENTRY"(
                                                  "ID" BINARY NOT NULL,
                                                  "ARCHIVED" BOOLEAN,
                                                  "CONGREGATION_POOL" BOOLEAN,
                                                  "MINISTERID" BINARY,
                                                  "MINISTER_NAME" VARCHAR(255),
                                                  "REGISTERED" TIMESTAMP,
                                                  "TERRITORYID" BINARY,
                                                  "TERRITORY_NAME" VARCHAR(255),
                                                  "TERRITORY_NUMBER" VARCHAR(255)
);
ALTER TABLE "PUBLIC"."TERRITORY_ENTRY" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_E" PRIMARY KEY("ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.TERRITORY_ENTRY;
CREATE CACHED TABLE "PUBLIC"."USER"(
                                       "ID" BINARY NOT NULL,
                                       "EMAIL" VARCHAR(255),
                                       "PASSWORD" VARCHAR(255),
                                       "USER_NAME" VARCHAR(255)
);
ALTER TABLE "PUBLIC"."USER" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_27E" PRIMARY KEY("ID");
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.USER;
INSERT INTO "PUBLIC"."USER" VALUES
(X'f02e2ca04c9a4398b929be54aff398f3', 'toBeSet', '$2a$10$BvA7tI9ZLnfGiI6bQ27krebH2cdJ.2nmeR3Aq82Rj4CfTk6iFAg/S', 'admin');
CREATE CACHED TABLE "PUBLIC"."USERS_ROLES"(
                                              "USER_ID" BINARY NOT NULL,
                                              "ROLE_ID" BINARY NOT NULL
);
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.USERS_ROLES;
INSERT INTO "PUBLIC"."USERS_ROLES" VALUES
(X'f02e2ca04c9a4398b929be54aff398f3', X'e536a769267141a38059187ab8ea1938');
CREATE CACHED TABLE "PUBLIC"."VERIFICATION_TOKEN"(
                                                     "ID" BINARY NOT NULL,
                                                     "EXPIRY_DATE" TIMESTAMP,
                                                     "TOKEN" VARCHAR(255),
                                                     "USER_ID" BINARY NOT NULL
);
ALTER TABLE "PUBLIC"."VERIFICATION_TOKEN" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_8" PRIMARY KEY("ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.VERIFICATION_TOKEN;
ALTER TABLE "PUBLIC"."TERRITORY" ADD CONSTRAINT "PUBLIC"."UK_4KWBVUVEJHLXG2BRW6BEFWIHH" UNIQUE("NUMBER");
ALTER TABLE "PUBLIC"."USER" ADD CONSTRAINT "PUBLIC"."UK_OB8KQYQQGMEFL0ACO34AKDTPE" UNIQUE("EMAIL");
ALTER TABLE "PUBLIC"."MINISTER" ADD CONSTRAINT "PUBLIC"."UK_EVDNHK2WXQ3BCICVY693RYWOF" UNIQUE("NAME");
ALTER TABLE "PUBLIC"."USER" ADD CONSTRAINT "PUBLIC"."UK_LQJRCOBRH9JC8WPCAR64Q1BFH" UNIQUE("USER_NAME");
ALTER TABLE "PUBLIC"."USERS_ROLES" ADD CONSTRAINT "PUBLIC"."FKGD3IENDAOYH04B95YKQISE6QH" FOREIGN KEY("USER_ID") REFERENCES "PUBLIC"."USER"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."ROLES_PRIVILEGES" ADD CONSTRAINT "PUBLIC"."FK9H2VEWSQH8LUHFQ71XOKH4WHO" FOREIGN KEY("ROLE_ID") REFERENCES "PUBLIC"."ROLE"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."ROLES_PRIVILEGES" ADD CONSTRAINT "PUBLIC"."FK5YJWXW2GVFYU76J3RGQWO685U" FOREIGN KEY("PRIVILEGE_ID") REFERENCES "PUBLIC"."PRIVILEGE"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."PASSWORD_RESET_TOKEN" ADD CONSTRAINT "PUBLIC"."FK5LWTBNCUG84D4ERO33V3CFXVL" FOREIGN KEY("USER_ID") REFERENCES "PUBLIC"."USER"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."USERS_ROLES" ADD CONSTRAINT "PUBLIC"."FKT4V0RRWEYK393BDGT107VDX0X" FOREIGN KEY("ROLE_ID") REFERENCES "PUBLIC"."ROLE"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."VERIFICATION_TOKEN" ADD CONSTRAINT "PUBLIC"."FK_VERIFY_USER" FOREIGN KEY("USER_ID") REFERENCES "PUBLIC"."USER"("ID") NOCHECK;
