name: BUILD RELEASE

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

          - name: Node ${{ matrix.node-version }}
            uses: actions/setup-node@v1
            with:
              node-version: ${{ matrix.node-version }}

          - name: npm ci and npm run build
            run: |
              cd src/main/ui
              npm ci
              npm run build:ci
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Download artifact
      uses: actions/download-artifact@v1.0.0
      with:
        # Artifact name
        name: finalministry-territories
