name: BUILD RELEASE

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Use Node.js 12.8
      uses: actions/setup-node@v1
      with:
        node-version: 12.8
    - name: Install and Build NPM
      run: |
        cd src/main/ui
        npm install
        npm run build -- --prod
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Make Directory and Copy Artifact
      run: |
        mkdir -p release;
        cp target/finalministry-territories-1.0.jar release/;
    - uses: actions/upload-artifact@master
        with:
          name: Finalministry-Territories-1.0
          path: release
